name: Security
on:
  push:
    branches:
      - main
      - 2.x-dev
      - 1.x
  pull_request: ~

jobs:
  security:
    uses: konradmichalik/reusable-github-actions/.github/workflows/security.yml@main
    permissions:
      contents: read
